### PR TITLE
Fix string interpolation problem

### PR DESCRIPTION
**Pull request by dm4**
This PR fix issue #180

### CODE REVIEW

**Comment by donavanbecker** [comment]
@dm4, can you test the latest beta and let me know if this is working now?

**Comment by dm4** [comment]
@donavanbecker sure, I'll test it later today.

**Comment by dm4** [comment]
Hi @donavanbecker,

I just manually installed beta branch and tested. The `setAll` command works great for my air condition:
```
[7/10/2021, 4:03:17 PM] [SwitchBot] Sending request for Air Conditioner to SwitchBot API. command: turnOff parameter: default commandType: command
[7/10/2021, 4:03:22 PM] [SwitchBot] Sending request for Air Conditioner to SwitchBot API. command: turnOn parameter: default commandType: command
[7/10/2021, 4:03:24 PM] [SwitchBot] Sending request for Air Conditioner to SwitchBot API. command: setAll parameter: 24,1,1,on commandType: command
[7/10/2021, 4:03:26 PM] [SwitchBot] Sending request for Air Conditioner to SwitchBot API. command: setAll parameter: 26,1,1,on commandType: command
```

**Comment by donavanbecker** [comment]
Can you look at latest comment from #180?

**Pull request merged**
